# Configuration for Sub-agent 4 Orchestrator (src/agents/sub_agents/sub_agent_4/agent.py)
# This file defines high-level settings for sub-agent 4.

agent_name: "SubAgent4_Specialist"
agent_id: "sub_agent_4"

# Description of this sub-agent's specific function or domain.
# Example: "Handles complex calculations and data processing tasks."
agent_description: "[Defina aqui a função específica do Sub-agente 4]"

# Default behavior settings for this sub-agent
default_language: "pt-BR"

# Feature flags specific to this sub-agent
feature_flags:
  log_sub_agent_trace: true

# Configuration for how this sub-agent should handle errors
error_handling:
  error_reporting_strategy: "return_error_message"
  default_error_prefix: "Erro no Sub-agente 4: "

