# Configuration for Sub-agent 3 Orchestrator (src/agents/sub_agents/sub_agent_3/agent.py)
# This file defines high-level settings for sub-agent 3.

agent_name: "SubAgent3_Specialist"
agent_id: "sub_agent_3"

# Description of this sub-agent's specific function or domain.
# Example: "Manages booking and reservation tasks."
agent_description: "[Defina aqui a função específica do Sub-agente 3]"

# Default behavior settings for this sub-agent
default_language: "pt-BR"

# Feature flags specific to this sub-agent
feature_flags:
  log_sub_agent_trace: true

# Configuration for how this sub-agent should handle errors
error_handling:
  error_reporting_strategy: "return_error_message"
  default_error_prefix: "Erro no Sub-agente 3: "

